name: mm_textiles_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^6.1.0
  get: ^4.6.6
  iconsax: ^0.0.8
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  animated_segmented_tab_control: ^2.0.0
  cached_network_image: ^3.4.1
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  # Backend packages
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  zoom_pinch_overlay: ^1.4.3
  iconify_flutter: ^0.0.7
  iconsax_flutter: ^1.0.1
  font_awesome_flutter: ^10.9.1
  flutter_file_downloader: ^2.1.0
  permission_handler: ^11.3.0
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Icons/
    - assets/Images/
